#!/usr/bin/env python3

import yaml
from pathlib import Path
import os
from uptodate import UpToDate

uptodate = UpToDate('.code_update_timestamp')

with open("subsidiary.yml", "r") as f:
    subsidary = yaml.safe_load(f)

destination = "/notes/biom2005/lectures/apb-lectures/code/"

for lecture in subsidary:
    for fileName in subsidary[lecture].values():
        if not uptodate(f"code/{fileName}"):
            continue
        dir = f"{destination}{lecture}"
        if not Path(f"code/{fileName}").exists():
            print(f"code/{fileName} does not exist")
            continue
        os.system(f"ssh login \"mkdir -p {dir}\"")
        os.system(f"scp code/{fileName} login:{dir}/{fileName}")

uptodate.done()
    
